// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AuthToken struct {
	ID        string         `json:"id"`
	TokenHash string         `json:"token_hash"`
	Name      string         `json:"name"`
	ExpiresAt sql.NullString `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
	CreatedBy string         `json:"created_by"`
}

type Config struct {
	ID                      int64          `json:"id"`
	Version                 string         `json:"version"`
	UpstreamUrl             string         `json:"upstream_url"`
	Port                    int64          `json:"port"`
	IdleTimeoutMs           int64          `json:"idle_timeout_ms"`
	MaxGenerationTimeMs     int64          `json:"max_generation_time_ms"`
	MaxUpstreamErrorRetries int64          `json:"max_upstream_error_retries"`
	MaxIdleRetries          int64          `json:"max_idle_retries"`
	MaxGenerationRetries    int64          `json:"max_generation_retries"`
	LoopDetectionJson       string         `json:"loop_detection_json"`
	ToolRepairJson          string         `json:"tool_repair_json"`
	UpdatedAt               string         `json:"updated_at"`
	UpstreamCredentialID    sql.NullString `json:"upstream_credential_id"`
	BufferSize              int64          `json:"buffer_size"`
}

type Credential struct {
	ID        string `json:"id"`
	Provider  string `json:"provider"`
	ApiKey    string `json:"api_key"`
	BaseUrl   string `json:"base_url"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Model struct {
	ID                         string         `json:"id"`
	Name                       string         `json:"name"`
	Enabled                    int64          `json:"enabled"`
	FallbackChainJson          string         `json:"fallback_chain_json"`
	TruncateParamsJson         string         `json:"truncate_params_json"`
	CreatedAt                  string         `json:"created_at"`
	UpdatedAt                  string         `json:"updated_at"`
	Internal                   int64          `json:"internal"`
	InternalProvider           sql.NullString `json:"internal_provider"`
	InternalApiKey             sql.NullString `json:"internal_api_key"`
	InternalBaseUrl            sql.NullString `json:"internal_base_url"`
	InternalModel              sql.NullString `json:"internal_model"`
	InternalKeyVersion         int64          `json:"internal_key_version"`
	CredentialID               sql.NullString `json:"credential_id"`
	ReleaseStreamChunkDeadline int64          `json:"release_stream_chunk_deadline"`
}
