// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Config struct {
	ID                      int64  `json:"id"`
	Version                 string `json:"version"`
	UpstreamUrl             string `json:"upstream_url"`
	Port                    int64  `json:"port"`
	IdleTimeoutMs           int64  `json:"idle_timeout_ms"`
	MaxGenerationTimeMs     int64  `json:"max_generation_time_ms"`
	MaxUpstreamErrorRetries int64  `json:"max_upstream_error_retries"`
	MaxIdleRetries          int64  `json:"max_idle_retries"`
	MaxGenerationRetries    int64  `json:"max_generation_retries"`
	LoopDetectionJson       string `json:"loop_detection_json"`
	UpdatedAt               string `json:"updated_at"`
}

type Model struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	Enabled            int64  `json:"enabled"`
	FallbackChainJson  string `json:"fallback_chain_json"`
	TruncateParamsJson string `json:"truncate_params_json"`
	CreatedAt          string `json:"created_at"`
	UpdatedAt          string `json:"updated_at"`
}
