// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countConfigs = `-- name: CountConfigs :one
SELECT COUNT(*) FROM configs
`

func (q *Queries) CountConfigs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModels = `-- name: CountModels :one
SELECT COUNT(*) FROM models
`

func (q *Queries) CountModels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteModel = `-- name: DeleteModel :exec
DELETE FROM models WHERE id = ?
`

func (q *Queries) DeleteModel(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteModel, id)
	return err
}

const getAllModels = `-- name: GetAllModels :many
SELECT id, name, enabled, fallback_chain_json, truncate_params_json, created_at, updated_at, internal, internal_provider, internal_api_key, internal_base_url, internal_model, internal_key_version, credential_id FROM models ORDER BY name
`

func (q *Queries) GetAllModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getAllModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.FallbackChainJson,
			&i.TruncateParamsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Internal,
			&i.InternalProvider,
			&i.InternalApiKey,
			&i.InternalBaseUrl,
			&i.InternalModel,
			&i.InternalKeyVersion,
			&i.CredentialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one
SELECT id, version, upstream_url, upstream_token, port, idle_timeout_ms, max_generation_time_ms, max_upstream_error_retries, max_idle_retries, max_generation_retries, loop_detection_json, updated_at FROM configs WHERE id = 1
`

func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i Config
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.UpstreamUrl,
		&i.UpstreamToken,
		&i.Port,
		&i.IdleTimeoutMs,
		&i.MaxGenerationTimeMs,
		&i.MaxUpstreamErrorRetries,
		&i.MaxIdleRetries,
		&i.MaxGenerationRetries,
		&i.LoopDetectionJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnabledModels = `-- name: GetEnabledModels :many
SELECT id, name, enabled, fallback_chain_json, truncate_params_json, created_at, updated_at, internal, internal_provider, internal_api_key, internal_base_url, internal_model, internal_key_version, credential_id FROM models WHERE enabled = 1 ORDER BY name
`

func (q *Queries) GetEnabledModels(ctx context.Context) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Model{}
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.FallbackChainJson,
			&i.TruncateParamsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Internal,
			&i.InternalProvider,
			&i.InternalApiKey,
			&i.InternalBaseUrl,
			&i.InternalModel,
			&i.InternalKeyVersion,
			&i.CredentialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModelByID = `-- name: GetModelByID :one
SELECT id, name, enabled, fallback_chain_json, truncate_params_json, created_at, updated_at, internal, internal_provider, internal_api_key, internal_base_url, internal_model, internal_key_version, credential_id FROM models WHERE id = ?
`

func (q *Queries) GetModelByID(ctx context.Context, id string) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByID, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.FallbackChainJson,
		&i.TruncateParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Internal,
		&i.InternalProvider,
		&i.InternalApiKey,
		&i.InternalBaseUrl,
		&i.InternalModel,
		&i.InternalKeyVersion,
		&i.CredentialID,
	)
	return i, err
}

const insertModel = `-- name: InsertModel :exec
INSERT INTO models (
    id,
    name,
    enabled,
    fallback_chain_json,
    truncate_params_json
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertModelParams struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	Enabled            int64  `json:"enabled"`
	FallbackChainJson  string `json:"fallback_chain_json"`
	TruncateParamsJson string `json:"truncate_params_json"`
}

func (q *Queries) InsertModel(ctx context.Context, arg InsertModelParams) error {
	_, err := q.db.ExecContext(ctx, insertModel,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.FallbackChainJson,
		arg.TruncateParamsJson,
	)
	return err
}

const updateConfig = `-- name: UpdateConfig :exec
UPDATE configs SET
    version = ?1,
    upstream_url = ?2,
    upstream_token = ?3,
    port = ?4,
    idle_timeout_ms = ?5,
    max_generation_time_ms = ?6,
    max_upstream_error_retries = ?7,
    max_idle_retries = ?8,
    max_generation_retries = ?9,
    loop_detection_json = ?10,
    updated_at = ?11
WHERE id = 1
`

type UpdateConfigParams struct {
	Version                 sql.NullString `json:"version"`
	UpstreamUrl             sql.NullString `json:"upstream_url"`
	UpstreamToken           sql.NullString `json:"upstream_token"`
	Port                    sql.NullInt64  `json:"port"`
	IdleTimeoutMs           sql.NullInt64  `json:"idle_timeout_ms"`
	MaxGenerationTimeMs     sql.NullInt64  `json:"max_generation_time_ms"`
	MaxUpstreamErrorRetries sql.NullInt64  `json:"max_upstream_error_retries"`
	MaxIdleRetries          sql.NullInt64  `json:"max_idle_retries"`
	MaxGenerationRetries    sql.NullInt64  `json:"max_generation_retries"`
	LoopDetectionJson       sql.NullString `json:"loop_detection_json"`
	UpdatedAt               sql.NullString `json:"updated_at"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateConfig,
		arg.Version,
		arg.UpstreamUrl,
		arg.UpstreamToken,
		arg.Port,
		arg.IdleTimeoutMs,
		arg.MaxGenerationTimeMs,
		arg.MaxUpstreamErrorRetries,
		arg.MaxIdleRetries,
		arg.MaxGenerationRetries,
		arg.LoopDetectionJson,
		arg.UpdatedAt,
	)
	return err
}

const updateModel = `-- name: UpdateModel :exec
UPDATE models SET
    name = ?,
    enabled = ?,
    fallback_chain_json = ?,
    truncate_params_json = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateModelParams struct {
	Name               string `json:"name"`
	Enabled            int64  `json:"enabled"`
	FallbackChainJson  string `json:"fallback_chain_json"`
	TruncateParamsJson string `json:"truncate_params_json"`
	ID                 string `json:"id"`
}

func (q *Queries) UpdateModel(ctx context.Context, arg UpdateModelParams) error {
	_, err := q.db.ExecContext(ctx, updateModel,
		arg.Name,
		arg.Enabled,
		arg.FallbackChainJson,
		arg.TruncateParamsJson,
		arg.ID,
	)
	return err
}
